name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/$GCP_PROJECT/my-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app --image gcr.io/$GCP_PROJECT/my-app --platform managed --region us-central1 --allow-unauthenticated
